theme: jekyll-theme-dinky
title: IOTA Full Node Documentation
email: nurielst@hotmail.com
description: Documentation for IOTA Full Node Auto-Installer
baseurl: /iri-playbook
github_username: nuriel77
mardown: kramdown
