# --- CentOS
- name: check jdk installed
  shell: "rpm -q jdk1.8-1.8.0_152-fcs.x86_64"
  register: check_jdk
  failed_when: false
  changed_when: false
  tags:
    - oracle_java_rpm

- name: Download java jdk rpm
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jdk-8u152-linux-x64.rpm"
    dest: /tmp/jdk-8u152-linux-x64.rpm
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    validate_certs: no
    force: yes
  when: check_jdk.rc == 1
  register: dl_oracle_java
  tags:
    - download_jdk_rpm
    - oracle_java_rpm

- name: yum install oracle java rpm
  yum:
    name: /tmp/jdk-8u152-linux-x64.rpm
    state: present
  when: dl_oracle_java.changed
  tags:
    - oracle_java_rpm

- name: remove local jdk rpm
  file:
    path: /tmp/jdk-8u152-linux-x64.rpm
    state: absent
  tags:
    - oracle_java_rpm

# Required
- name: Install epel-release
  yum: state=latest name=epel-release

- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - policycoreutils-python
    - maven
    - libappindicator
    - firewalld
    - curl
    - lsof
    - jq
